package user;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import java.util.*;

@DynamoDBTable(tableName=Config.DYNAMODB_TABLE_NAME)
public class User {
	private UUID id;
	private String name;
	private String email;
	private String password;
	private double total = 0.0;
	private double bankAccount = 0.0;
	private double crypto = 0.0;
	private double savingAccount = 0.0;
	private List<Double> transactions = new ArrayList<>();
	private List<String> userTransactions = new ArrayList<>();

	private final double BITCOIN_PRICE = 6125.59;
	public User() {	}
	
	public User(String name, String email, String password, double bankAccount) {
		this.setId(UUID.randomUUID());
		this.setName(name);
		this.setEmail(email);
		this.setPassword(password);
		this.setBankAccount(bankAccount);
		this.setTotal(this.getCrypto() + this.getBankAccount() + this.getSavingAccount());
	}
	
	public User(UUID id, String name, String email, String password, double bankAccount) { 
		this.setId(id);
		this.setName(name);
		this.setEmail(email);
		this.setPassword(password);
		this.setBankAccount(bankAccount);
		this.setTotal((this.getCrypto() * BITCOIN_PRICE) + this.getBankAccount() + this.getSavingAccount());
	}
	
	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public UUID getId() {
		return this.id;
	} 
	
	@DynamoDBAttribute(attributeName="name")
	public String getName() {
		return this.name;
	} 
	
	@DynamoDBAttribute(attributeName="email")
	public String getEmail() {
		return this.email;
	} 
	
	@DynamoDBAttribute(attributeName="password")
	public String getPassword() {
		return this.password;
	} 
	
	@DynamoDBAttribute(attributeName="transactions")
	public List<Double> getTransactions() {
		return this.transactions;
	} 

	@DynamoDBAttribute(attributeName="transactionsName")
	public List<String> getUserTransactions() {
		return userTransactions;
	}

	@DynamoDBAttribute(attributeName="savingAccount")
	public double getSavingAccount() {
		return savingAccount;
	}
	
	@DynamoDBAttribute(attributeName="bankAccount")
	public double getBankAccount() {
		return bankAccount;
	}

	@DynamoDBAttribute(attributeName="cryptoAccount")
	public double getCrypto() {
		return crypto;
	}

	public double getTotal() {
		return total;
	}

	public void addTransaction(double transaction) {
		this.transactions.add(transaction);
	}


	public void setTotal(double total) {
		this.total = total;
	}


	public void setBankAccount(double bankAccount) {
		this.bankAccount = bankAccount;
	}

	public void setCrypto(double crypto) {
		this.crypto = crypto;
	}


	public void setSavingAccount(double savingAccount) {
		this.savingAccount = savingAccount;
	}


	public void setUserTransactions(List<String> userTransactions) {
		this.userTransactions = userTransactions;
	}
	
	public void setId(UUID newId) {
		this.id = newId; 
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public void setTransactions(List<Double> transactions) {
		this.transactions = transactions;
	}

	
}
